version: '3.9'

services:
  db-endereco:
    image: postgres:16.2
    restart: always
    container_name: BotCryptoCoin
    environment:
      POSTGRES_DB: CryptoCoin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - C:/Projetos/PostgresData/CryptoCoin:/var/lib/postgresql/data
